// export const types = {
//   login: '[auth] login',
//   logout: '[auth] logout',
// };

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const VALIDATE_PASSWORD_ERROR = 'VALIDATE_PASSWORD_ERROR';
export const VALIDATE_PASSWORD_EXITOSO = 'VALIDATE_PASSWORD_EXITOSO';
export const UPDATE_PASSWORD_EXITOSO = 'UPDATE_PASSWORD_EXITOSO';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';
export const UPDATE_PROFILE_EXITOSO = 'UPDATE_PROFILE_EXITOSO';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const UPDATE_PROFILE_SHOW = 'UPDATE_PROFILE_SHOW';
export const UPDATE_PROFILE_HIDE = 'UPDATE_PROFILE_HIDE';

